name: 'ci'

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node_version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build
